scripts/addons/cam/opencamlib/opencamlib.py

I'm trying to compile opencamlib under Arch, and I have some issues, so I cant do any test. But I saw this line and seemed strange.

I this an error?

---

scripts/addons/cam/utils.py

- moved drill strategy into its own function
- If use layers is enabled then peck drilling is performed using layer
stepdown depth.
- if using object depth is enabled then the individual object depth is
used. If using points then the point z value determines the depth of
drilling for that location.  Otherwise the operation depth is used for
all objects/points.
- operation depth start is used for the retraction height during peck
drilling.
- Retraction feed rate is normal feed rate.  Drilling feed rate is the
plunge feed rate.

Drill cycle Enhancements

---

scripts/addons/cam/ui.py

Fix the panel "CAM info & warnings" display time of the NC program

Fix the panel "CAM info & warnings" display time of the NC program

---

.gitignore
scripts/addons/cam/utils.py

See detailed comments and a couple images in comment below code changes.

Modified MEDIAL AXIS strategy for VCARVE bits to honor the operation depth start and end values.

---

scripts/addons/cam/__init__.py
scripts/addons/cam/nc/fadal.py
scripts/addons/cam/nc/heiden530.py
scripts/addons/cam/utils.py

Fadal machines and Heidenhain controls postprocesor 2.80

---

scripts/addons/cam/collision.py
scripts/addons/cam/utils.py

fix vcarve

---

scripts/addons/cam/image_utils.py
scripts/addons/cam/testing.py
scripts/addons/cam/utils.py

view_align False deprecated new align" WORLD"

---

scripts/addons/cam/opencamlib/oclSample.py
scripts/addons/cam/opencamlib/opencamlib.py

this is very early working state :P
it will require to install opencamlib inside blender
described here
https://github.com/vilemduha/blendercam/wiki/Install-opencamlib-into-blender-2.80-on-linux#installing-opencamlib-in-blender

Use opencamlib from blender python interpreter [WIP]

---

README.md
scripts/addons/cam/image_utils.py

correct developmen link on readme

---

scripts/addons/cam/image_utils.py

this fixes waterline oprations
many thanks to @palain

fix waterline by @palain

---

scripts/addons/cam/__init__.py
scripts/addons/cam/ui.py
scripts/addons/cam/utils.py

bridges now work above 0 below 0 and in between.

Fixed bridges

---

scripts/addons/cam/ops.py
scripts/addons/cam/utils.py

pulled in the middle of updating

---

scripts/addons/cam/opencamlib/oclSample.py
scripts/addons/cam/ui.py
scripts/addons/cam/utils.py

Ballcone fix: rotation A rotation B improved check

---

.gitignore
scripts/addons/cam/__init__.py

hello,
this commit got overriden by the last merge :P
thanks

set min spindle speed to 0

---

scripts/addons/cam/__init__.py
scripts/addons/cam/collision.py
scripts/addons/cam/curvecamcreate.py
scripts/addons/cam/joinery.py
scripts/addons/cam/slice.py
scripts/addons/cam/ui_panels/area.py
scripts/addons/cam/ui_panels/cutter.py

few fixes in general maintenance

march 2023 bug fixes

---

scripts/__init__.py
scripts/addons/cam/__init__.py
scripts/addons/cam/backgroundop.py_
scripts/addons/cam/chunk.py
scripts/addons/cam/collision.py
scripts/addons/cam/constants.py
scripts/addons/cam/gcodepath.py
scripts/addons/cam/image_utils.py
scripts/addons/cam/ops.py
scripts/addons/cam/pattern.py
scripts/addons/cam/simulation.py
scripts/addons/cam/strategy.py
scripts/addons/cam/testing.py
scripts/addons/cam/ui.py
scripts/addons/cam/ui_panels/buttons_panel.py
scripts/addons/cam/ui_panels/cutter.py
scripts/addons/cam/ui_panels/info.py
scripts/addons/cam/ui_panels/material.py
scripts/addons/cam/ui_panels/op_properties.py
scripts/addons/cam/ui_panels/operations.py
scripts/addons/cam/ui_panels/optimisation.py
scripts/addons/cam/utils.py

several bug fixes and code cleanup

may cleanup

---

scripts/addons/cam/__init__.py
scripts/addons/cam/chunk.py
scripts/addons/cam/gcodepath.py
scripts/addons/cam/image_utils.py
scripts/addons/cam/ops.py
scripts/addons/cam/pattern.py
scripts/addons/cam/slice.py
scripts/addons/cam/strategy.py
scripts/addons/cam/testing.py
scripts/addons/cam/ui.py
scripts/addons/cam/ui_panels/area.py
scripts/addons/cam/ui_panels/buttons_panel.py
scripts/addons/cam/ui_panels/cutter.py
scripts/addons/cam/ui_panels/info.py
scripts/addons/cam/ui_panels/machine.py
scripts/addons/cam/ui_panels/material.py
scripts/addons/cam/ui_panels/movement.py
scripts/addons/cam/ui_panels/op_properties.py
scripts/addons/cam/ui_panels/operations.py
scripts/addons/cam/ui_panels/optimisation.py
scripts/addons/cam/utils.py

june 15 2023 maintenance

---

documentation/Getting started.md

References markdown file removed 6 months ago.

Remove broken opencamlib link

---

documentation/Blendercam Installation.md

A couple links in the old table of contents didn't work, so I've just fixed them to reflect the new sections

Fixed Table of Contents and a section title in Blendercam Installation.md

---

README.md

Also document, that it is compatible with MacOS

Update Readme, add link to BlenderCAM website.
